name: Resume Sync Workflow

on:
  workflow_dispatch:

jobs:
  sync_resumes:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
      GOOGLE_TOKEN: ${{ secrets.GOOGLE_TOKEN }}
      DROPBOX_CREDS: ${{ secrets.DROPBOX_CREDS }}
      DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Resume Sync Script
      run: python ./resume-sync/resume_sync.py
