name: Resume Sync Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'  # 10:00 AM UTC = 5:00 AM EST
    

jobs:
  sync_resumes:
    runs-on: ubuntu-latest
    env:
      # GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
      # GOOGLE_TOKEN: ${{ secrets.GOOGLE_TOKEN }}
      GOOGLE_SA_KEY: ${{ secrets.GOOGLE_SA_KEY }}
      DROPBOX_CREDS: ${{ secrets.DROPBOX_CREDS }}
      DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Resume Sync Script
      run: python ./resume-sync/resume_sync.py
